### ISSUE TITLE
appservice fails to create database

### ISSUE THREAD

**Issue by Cknight70** [git-bruh/matrix-discord-bridge#10]
For the appservice ``python3 main.py`` finishes immediately, this is the result in the log:
```
2021-10-04 17:33:43 root:CRITICAL:Unknown exception:
Traceback (most recent call last):
  File "/opt/appservice/main.py", line 751, in <module>
    main()
  File "/opt/appservice/main.py", line 736, in main
    app = MatrixClient(config, urllib3.PoolManager(maxsize=10))
  File "/opt/appservice/main.py", line 27, in __init__
    self.db = DataBase(config["database"])
  File "/opt/appservice/db.py", line 9, in __init__
    self.create(db_file)
  File "/opt/appservice/db.py", line 21, in create
    self.conn = sqlite3.connect(db_file, check_same_thread=False)
sqlite3.OperationalError: unable to open database file
```

I manually created the database and everything seems to work fine now

**Comment by git-bruh** [comment]
Did you have permissions to open the database ? You've put the python files in /opt so the user running the process might not have access to that directory

**Comment by Cknight70** [comment]
That may be the case, I have file permissions set correctly there now, but when trying to re-create this in another directory I was not able to. Thank you for your project, it was simple to setup and works well.
