### ISSUE TITLE
Percent encoded identifiers do not ping Discord users

### ISSUE THREAD

**Issue by Cknight70** [git-bruh/matrix-discord-bridge#12]
I'm using your puppeting appservice.
When I type @ and slelect a Discord user to try to ping using nheko, the ping is only text on the Discord side. 

![image](https://user-images.githubusercontent.com/28763729/144141441-d9ac829c-31cc-484c-8a19-8029953da2a1.png)
![image](https://user-images.githubusercontent.com/28763729/144141478-1ad8e7dc-d614-45ff-ac35-34d457393ba8.png)

nheko encodes its identifiers using percent encoding as opposed to Element, which I have been told is the correct way according to the Matrix spec https://spec.matrix.org/v1.1/appendices/#matrixto-navigation

element sends ``https://matrix.to/#/@_discord_123456789:myserver.com``
nheko sends ``https://matrix.to/#/%40_discord_123456789%3Amyserver.com``

More info can be found in my bug report for nheko
https://github.com/Nheko-Reborn/nheko/issues/832#issuecomment-983137721

**Comment by git-bruh** [comment]
Hi, please try this patch https://termbin.com/oa0uk and let me know if it works so I can commit it.

**Comment by Cknight70** [comment]
Thank you, I cleared my pycache and previous appservice log before running with the patch.

When running with this patch, I get an error. My messages sent from Matrix are not sent to Discord. Discord messages are sent to Matrix.
My log file so far since applying the patch: 
```
2021-11-30 21:14:00 discord:INFO:Heartbeat Interval: 41250
2021-11-30 21:14:00 discord:INFO:READY
2021-11-30 21:15:48 discord:INFO:Updating avatar for Discord user '863087949239419503'
2021-11-30 21:15:50 appservice:ERROR:Exception in 'receive_event':
Traceback (most recent call last):
  File "/opt/appservice/misc.py", line 28, in wrapper
    return fn(self, *args, **kwargs)
  File "/opt/appservice/appservice.py", line 87, in receive_event
    self.handle_event(event)
  File "/opt/appservice/appservice.py", line 66, in handle_event
    func(obj)
  File "/opt/appservice/main.py", line 128, in on_message
    else self.process_message(message)
  File "/opt/appservice/main.py", line 352, in process_message
    mentions.extend(self.mention_regex(encode=True), event.formatted_body)
TypeError: list.extend() takes exactly one argument (2 given)
2021-11-30 21:17:17 discord:INFO:Updating avatar for Discord user '863087949239419503'
2021-11-30 21:20:48 appservice:ERROR:Exception in 'receive_event':
Traceback (most recent call last):
  File "/opt/appservice/misc.py", line 28, in wrapper
    return fn(self, *args, **kwargs)
  File "/opt/appservice/appservice.py", line 87, in receive_event
    self.handle_event(event)
  File "/opt/appservice/appservice.py", line 66, in handle_event
    func(obj)
  File "/opt/appservice/main.py", line 128, in on_message
    else self.process_message(message)
  File "/opt/appservice/main.py", line 352, in process_message
    mentions.extend(self.mention_regex(encode=True), event.formatted_body)
TypeError: list.extend() takes exactly one argument (2 given)
```

In case it is useful, I am running Debian 11 with python 3.9.2-3

**Comment by git-bruh** [comment]
@Cknight70  whoops, i forgot to run re.findall() . do `git stash` and try this one: https://termbin.com/akfq

**Comment by git-bruh** [comment]
@Cknight70 Sorry i probably should've been less lazy and tested it myself. Should work with the latest commit.

**Comment by Cknight70** [comment]
@git-bruh  Hello, I just tried this with your latest commit, and it seems to work the same way still. 
![image](https://user-images.githubusercontent.com/28763729/144182066-233b3a3f-7909-4e2a-8adb-d936bb846013.png)

**Comment by git-bruh** [comment]
Sorry! It's been a while since I worked on this project. It was passing the encoded username as a query to the database which uses decoded usernames so of course it didn't work! The latest commit should hopefully fix it. Tested it with element devtoools custom event.

**Comment by Cknight70** [comment]
Yes, it works now. Thank you :)
