### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by ZyxerZyxani** [git-bruh/matrix-discord-bridge#13]
I have set up the bot and tried to run it on my desktop, works. Copy config file over to RPi and try to run it there, but then it cannot send any messages to discord, only from discord channel to matrix room.  I got it using git clone on the pi

**Comment by ZyxerZyxani** [comment]
It doesn't seem to even listen to matrix, sending anything in matrix gives no error or anything.

**Comment by git-bruh** [comment]
Are you using the appservice or the regular bridge? Share your config file aswell

**Comment by ZyxerZyxani** [comment]
> 

pwd = /home/user/git/matrix-discord-bridge/bridge
command = python3 bridge.py

config.json
`{
    "homeserver": "https://matrix.zyxer.se",
    "username": "@zyxer:matrix.zyxer.se",
    "password": "secret password",
    "token": "Super secret token",
    "discord_cmd_prefix": "!?",
    "bridge": {
        "873378583555473418": "!JdvTbWPozsEkUiSYuf:matrix.zyxer.se",
	"870440102797660202": "!DwCqecuSkwaRILIovE:matrix.zyxer.se",
	"846867483402829893": "!qvYDFffFZXFvKfxyym:matrix.zyxer.se"
    }
}
`

Bot is only in one discord channel atm.
When I run it on desktop and I send message in a matrix room that is bridged to a channel the bot has no access to then it spits out error. When I do the same when running on my RPi it doesn't react at all. And also no message in discord channel that it has access too and no error message either. 
Yes, I double checked that I do not accidentally run it on desktop and RPi at the same time.

**Comment by ZyxerZyxani** [comment]
Python version 3.7

**Comment by git-bruh** [comment]
The bridge logs to a `bridge.log` file aswell, could you check the contents of it?

**Comment by ZyxerZyxani** [comment]
cat bridge.log


2021-12-26 13:59:00 discord.client:WARNING: PyNaCl is not installed, voice will NOT be supported
2021-12-26 13:59:00 discord.client:INFO: logging in using static token
2021-12-26 13:59:00 discord.gateway:INFO: Shard ID None has sent the IDENTIFY payload.
2021-12-26 13:59:01 discord.gateway:INFO: Shard ID None has connected to Gateway: ["gateway-prd-main-h86g",{"micros":79243,"calls":["discord-sessions-blue-prd-2-89",{"micros":77635,"calls":["start_session",{"micros":26319,"calls":["api-prd-main-7z0b",{"micros":23214,"calls":["get_user",{"micros":2378},"add_authorized_ip",{"micros":1276},"get_guilds",{"micros":3927},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":0,"calls":[]}]}]}] (Session ID: dba678b097dc62bcda0c656dc733cec1).
2021-12-26 13:59:01 matrix_logger:INFO: Logged in as @zyxer:matrix.zyxer.se, device id: DMEKEETBHF.
2021-12-26 13:59:04 matrix_logger:INFO: Clients ready!
2021-12-26 14:05:14 discord.client:WARNING: PyNaCl is not installed, voice will NOT be supported
2021-12-26 14:05:14 discord.client:INFO: logging in using static token
2021-12-26 14:05:14 discord.gateway:INFO: Shard ID None has sent the IDENTIFY payload.
2021-12-26 14:05:14 matrix_logger:INFO: Logged in as @zyxer:matrix.zyxer.se, device id: KQQUXUUCFS.
2021-12-26 14:05:15 matrix_logger:INFO: Clients ready!
2021-12-26 14:05:15 discord.gateway:INFO: Shard ID None has connected to Gateway: ["gateway-prd-main-rhrd",{"micros":84210,"calls":["discord-sessions-blue-prd-2-34",{"micros":83442,"calls":["start_session",{"micros":74872,"calls":["api-prd-main-cz98",{"micros":65239,"calls":["get_user",{"micros":7765},"add_authorized_ip",{"micros":2398},"get_guilds",{"micros":14453},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: cde0ca400bd657ca84f0e9fb7d5604ed).
2021-12-26 15:08:25 discord.client:WARNING: PyNaCl is not installed, voice will NOT be supported
2021-12-26 15:08:25 discord.client:INFO: logging in using static token
2021-12-26 15:08:25 discord.gateway:INFO: Shard ID None has sent the IDENTIFY payload.
2021-12-26 15:08:26 discord.gateway:INFO: Shard ID None has connected to Gateway: ["gateway-prd-main-z7w9",{"micros":90145,"calls":["discord-sessions-blue-prd-2-137",{"micros":88606,"calls":["start_session",{"micros":34266,"calls":["api-prd-main-hq6h",{"micros":31568,"calls":["get_user",{"micros":2944},"add_authorized_ip",{"micros":1296},"get_guilds",{"micros":3508},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":29956,"calls":[]}]}]}] (Session ID: 222babde073d784361de8607050f06d9).
2021-12-26 15:08:26 matrix_logger:INFO: Logged in as @zyxer:matrix.zyxer.se, device id: MAVTJGPOBG.
2021-12-26 15:08:26 matrix_logger:INFO: Clients ready!
2021-12-26 15:10:40 discord.client:WARNING: PyNaCl is not installed, voice will NOT be supported
2021-12-26 15:10:40 discord.client:INFO: logging in using static token
2021-12-26 15:10:41 matrix_logger:INFO: Logged in as @zyxer:matrix.zyxer.se, device id: LEUYNGGXZQ.
2021-12-26 15:10:41 discord.gateway:INFO: Shard ID None has sent the IDENTIFY payload.
2021-12-26 15:10:41 matrix_logger:INFO: Clients ready!
2021-12-26 15:10:41 discord.gateway:INFO: Shard ID None has connected to Gateway: ["gateway-prd-main-fp1c",{"micros":60837,"calls":["discord-sessions-blue-prd-2-136",{"micros":60066,"calls":["start_session",{"micros":58244,"calls":["api-prd-main-w2f4",{"micros":51545,"calls":["get_user",{"micros":5080},"add_authorized_ip",{"micros":4183},"get_guilds",{"micros":7997},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":1332,"calls":[]}]}]}] (Session ID: e04adffffb1c137757cea642ab0e52ce).
2021-12-26 15:11:59 asyncio:ERROR: SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0xb4ac0a70>
transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-12-26 15:16:54 discord.client:WARNING: PyNaCl is not installed, voice will NOT be supported
2021-12-26 15:16:54 discord.client:INFO: logging in using static token
2021-12-26 15:16:54 discord.gateway:INFO: Shard ID None has sent the IDENTIFY payload.
2021-12-26 15:16:54 matrix_logger:INFO: Logged in as @zyxer:matrix.zyxer.se, device id: KTSPFCGNFG.
2021-12-26 15:16:55 discord.gateway:INFO: Shard ID None has connected to Gateway: ["gateway-prd-main-b2nk",{"micros":120835,"calls":["discord-sessions-blue-prd-2-157",{"micros":120039,"calls":["start_session",{"micros":80498,"calls":["api-prd-main-wvwp",{"micros":76483,"calls":["get_user",{"micros":5818},"add_authorized_ip",{"micros":5159},"get_guilds",{"micros":23417},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":29625,"calls":[]}]}]}] (Session ID: e7d018b085d150b087e9c862aed80954).
2021-12-26 15:16:55 matrix_logger:INFO: Clients ready!

**Comment by git-bruh** [comment]
Seems to be working fine. If `@zyxer:matrix.zyxer.se` is the same account which the bridge is logged on, and is the same account you're sending the messages from, it won't work. So you should create a seperate bot account for the bridge.

This is necessary as the bridge user relays discord messages aswell. So if the bridge user started responding to it's own messages, it would result in an infinite loop.

**Comment by ZyxerZyxani** [comment]
Yes. I have a separate account for bot and other account. 
It sends correctly when I run it from desktop. 

For example when sending in any room except the first bridged places, I get this on desktop:

2021-12-26 16:51:19 matrix_logger:ERROR: Unknown exception occured, retrying in 2 seconds...
Traceback (most recent call last):
  File "/home/emilio/git/matrix-discord-bridge/bridge/bridge.py", line 577, in main
    await matrix_client.sync_forever(timeout=30000, full_state=True)
  File "/usr/lib/python3.10/site-packages/nio/client/async_client.py", line 1185, in sync_forever
    await self.run_response_callbacks([await response])
  File "/usr/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/usr/lib/python3.10/site-packages/nio/client/async_client.py", line 1032, in sync
    response = await self._send(
  File "/usr/lib/python3.10/site-packages/nio/client/async_client.py", line 778, in _send
    await self.receive_response(resp)
  File "/usr/lib/python3.10/site-packages/nio/client/async_client.py", line 690, in receive_response
    await self._handle_sync(response)
  File "/usr/lib/python3.10/site-packages/nio/client/async_client.py", line 657, in _handle_sync
    await self._handle_joined_rooms(response)
  File "/usr/lib/python3.10/site-packages/nio/client/async_client.py", line 595, in _handle_joined_rooms
    await asyncio.coroutine(cb.func)(room, event)
  File "/home/emilio/git/matrix-discord-bridge/bridge/bridge.py", line 507, in typing_callback
    async with self.discord_client.channel_store[channel_id].typing():
AttributeError: 'NoneType' object has no attribute 'typing'

Because the bot is not in those discord channels. 
When sending in the first bridged room it sends whatever message or image I sent to the discord channel, not happening on RPi

**Comment by git-bruh** [comment]
> It sends correctly when I run it from desktop.

As in, matrix messages reach discord and discord messages reach matrix?

> Because the bot is not in those discord channels.

Then you should remove the channels from the config file, else it would constantly retry and not be able to relay any messages from matrix

> When sending in the first bridged room it sends whatever message or image I sent to the discord channel, not happening on RPi

Is there anything in `bridge.log` or logged to the terminal in this case?

**Comment by ZyxerZyxani** [comment]
Yes, when running from desktop matrix messages reach discord and discord messages reach matrix.

No, nothing is logged in the RPi.

**Comment by git-bruh** [comment]
Did you try to remove the channels that the bot has not joined in, and restart the bot?

**Comment by ZyxerZyxani** [comment]
Yes. Still not work

**Comment by git-bruh** [comment]
Could you download this patch https://termbin.com/70ty and `git apply` it and restart? I added some print() logging so it will tell you when a message is being sent or ignored. You can revert the changes with `git stash`.

**Comment by ZyxerZyxani** [comment]
Ok so I was in the middle of installing python 3.10 when you said that. And now it works, using python 3.10. 

However requirements gave errors so I had to pip install without specifying version number.
Error when trying to install requirements.txt:

ERROR: Cannot install -r requirements.txt (line 3) and aiofiles==0.6.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested aiofiles==0.6.0
    matrix-nio 0.17.0 depends on aiofiles<0.5.0 and >=0.4.0

**Comment by git-bruh** [comment]
Yes that's fine, matrix-nio for some reason has an old requirement for aiofiles, but works fine with the latest so you manually have to install aiofiles 0.6.0

Please close the issue if it's fixed now.
