### ISSUE TITLE
Unable to send messages over the bridge

### ISSUE THREAD

**Issue by kajatak** [git-bruh/matrix-discord-bridge#18]
I'm trying to use the basic bridge and the bot joins both channels however when I send a message on Matrix/Element nothing happens, and when I send a message in Discord I get the following error:

```Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/username/matrix-discord-bridge/bridge/bridge.py", line 281, in on_message
    matrix_message = await self.matrix_client.message_send(
  File "/home/username/matrix-discord-bridge/bridge/bridge.py", line 189, in message_send
    return message.event_id
AttributeError: 'RoomSendError' object has no attribute 'event_id'
```
I think everything should be set up correctly, so I'm not sure how to fix this. All help appreciated.

**Comment by kajatak** [comment]
Oof, I had my Matrix room set to posting for Moderators and up only, and had forgotten to promote the bot. Everything works fine now, sorry.
