### ISSUE TITLE
Feature request: Ability to use same Matrix room for a new Discord channel

### ISSUE THREAD

**Issue by Cknight70** [git-bruh/matrix-discord-bridge#20]
Hi, first off thanks for the bot, I've been using the puppeting appservice for a while now.

I tried a few different things and learned this is not a trival thing for an end user to do. Sorry if this is an unreasonable request but it would be greatly appreciated.

The TL;DR is we recently decided to create a new general channel on Discord, but it would be nice to keep the extended history in one room on Matrix. 

Some things I tried in case you are curious: changing the room id in the database, (is it even used?). 

Tried changing the room address manually to the new discord channel id in the correct format (eg #_discord_12323456:myserver.com ) but it seems only appservices can do this

Tried to figure out how to get an appservice to add a new address to an existing room, I wasn't able to find the documentation to do so.

Asked for help from my friend who has decent coding experience and tried to rewrite/make a hack to get this to work, by adding a new db column, which partially worked, but weren't able to get messages to send back to Discord.

Thanks again

**Comment by git-bruh** [comment]
I think you should be able to just alter the db in-place:

```sh
(env) ~/.../matrix-discord-bridge/appservice $ sqlite3 bridge.db
SQLite version 3.40.1 2022-12-28 14:03:47
Enter ".help" for usage hints.
sqlite> SELECT * FROM bridge;
!asdf:xyz.org|1234
sqlite> UPDATE bridge SET channel_id = 5678 WHERE room_id = "!asdf:xyz.org";
sqlite> SELECT * FROM bridge;
!asdf:xyz.org|5678
sqlite>
```

1234 is the old channel id and 5678 is the new one

Let me know if you still have issues.

**Comment by Cknight70** [comment]
Hi, unfortunately when I tried this it still looks for the old channel id, supposedly because of the alias of the room.
```
2023-02-18 12:21:36 appservice:ERROR:Exception in 'receive_event':
Traceback (most recent call last):
  File "/opt/appservice/misc.py", line 28, in wrapper
    return fn(self, *args, **kwargs)
  File "/opt/appservice/appservice.py", line 88, in receive_event
    self.handle_event(event)
  File "/opt/appservice/appservice.py", line 67, in handle_event
    func(obj)
  File "/opt/appservice/main.py", line 104, in on_message
    webhook = self.discord.get_webhook(
  File "/opt/appservice/main.py", line 632, in get_webhook
    webhooks = self.send("GET", f"/channels/{channel_id}/webhooks")
  File "/opt/appservice/misc.py", line 49, in wrapper
    raise RequestError(
errors.RequestError: Failed to get response from 'https://discord.com/api/v8/channels/OLDCHANNELIDNUMBERS/webhooks?':
b'{"message": "Unknown Channel", "code": 10003}'
```

**Comment by Cknight70** [comment]
```
b'{"errcode":"M_NOT_FOUND","error":"Room alias #_discord_1058054496112095343:cutefunny.art not found"}'
2023-02-18 14:12:26 discord:ERROR:Ignoring exception in 'on_message_create':
Traceback (most recent call last):
  File "/opt/appservice/gateway.py", line 129, in handle_otype
    func(obj)
  File "/opt/appservice/main.py", line 549, in on_message_create
    mxid, room_id = self.wrap(message)
  File "/opt/appservice/main.py", line 491, in wrap
    room_id = self.app.get_room_id(self.matrixify(message.channel_id))
  File "/opt/appservice/appservice.py", line 123, in get_room_id
    resp = self.send("GET", f"/directory/room/{urllib.parse.quote(alias)}")
  File "/opt/appservice/misc.py", line 49, in wrapper
    raise RequestError(
errors.RequestError: Failed to get response from 'http://127.0.0.1:8008/_matrix/client/r0/directory/room/%23_discord_1058054496112095343%3Acutefunny.art?':
```
this one too

**Comment by Cknight70** [comment]
This one too
```
b'{"errcode":"M_NOT_FOUND","error":"Room alias #_discord_NEWDISCORDCHANNEL:myserver.com not found"}'
2023-02-18 14:12:26 discord:ERROR:Ignoring exception in 'on_message_create':
Traceback (most recent call last):
  File "/opt/appservice/gateway.py", line 129, in handle_otype
    func(obj)
  File "/opt/appservice/main.py", line 549, in on_message_create
    mxid, room_id = self.wrap(message)
  File "/opt/appservice/main.py", line 491, in wrap
    room_id = self.app.get_room_id(self.matrixify(message.channel_id))
  File "/opt/appservice/appservice.py", line 123, in get_room_id
    resp = self.send("GET", f"/directory/room/{urllib.parse.quote(alias)}")
  File "/opt/appservice/misc.py", line 49, in wrapper
    raise RequestError(
errors.RequestError: Failed to get response from 'http://127.0.0.1:8008/_matrix/client/r0/directory/room/%23_discord_NEWDISCORDCHANNEL%3Amyserver.com?':
```

**Comment by git-bruh** [comment]
Hmm, it's probably gonna need some more intrusive hacks..

The first log doesn't make sense since the discord ID is being fetched from the database directly, so re confirm if the change was actually made in the sqlite database.

For the second error:

```diff
diff --git a/appservice/main.py b/appservice/main.py
index 4c635fe..0d683f0 100644
--- a/appservice/main.py
+++ b/appservice/main.py
@@ -478,6 +478,9 @@ class DiscordClient(Gateway):
         )
 
     def matrixify(self, id: str, user: bool = False, hashed: str = "") -> str:
+        if id == OLD_ID:
+            id = NEW_ID
+
         return (
             f"{'@' if user else '#'}{self.app.format}"
             f"{id}{'-' + hashed if hashed else ''}:"
```

**Comment by Cknight70** [comment]
Sorry for the first error it seemed it just took a second for it to update, for the second error, I get a new error when I apply this patch. Did you want me to make some new colmns in the database?

```
2023-02-19 16:17:20 discord:ERROR:Ignoring exception in 'on_guild_create':
Traceback (most recent call last):
  File "/opt/matrix-discord-bridge-new/gateway.py", line 129, in handle_otype
    func(obj)
  File "/opt/matrix-discord-bridge-new/main.py", line 563, in on_guild_create
    self.sync_profile(member)
  File "/opt/matrix-discord-bridge-new/main.py", line 495, in sync_profile
    mxid = self.matrixify(user.id, user=True, hashed=hashed)
  File "/opt/matrix-discord-bridge-new/main.py", line 481, in matrixify
    if id == OLD_ID:
NameError: name 'OLD_ID' is not defined
```

**Comment by git-bruh** [comment]
I meant that you need to substitute old_id with "1234" and new with "5678"
The bridge doesn't support yoir use case so this way we just hardcode the relation in the bridge logic

**Comment by Cknight70** [comment]
Thanks for the help, but unfortunately that didn't work either.
```
b'{"errcode":"M_NOT_FOUND","error":"Room alias #_discord_NEW_ID:myserver.com not found"}'
2023-02-21 00:46:01 discord:ERROR:Ignoring exception in 'on_message_create':
Traceback (most recent call last):
  File "/opt/matrix-discord-bridge-new/gateway.py", line 129, in handle_otype
    func(obj)
  File "/opt/matrix-discord-bridge-new/main.py", line 581, in on_message_create
    mxid, room_id = self.wrap(message)
  File "/opt/matrix-discord-bridge-new/main.py", line 523, in wrap
    room_id = self.app.get_room_id(self.matrixify(message.channel_id))
  File "/opt/matrix-discord-bridge-new/appservice.py", line 122, in get_room_id
    resp = self.send("GET", f"/directory/room/{urllib.parse.quote(alias)}")
  File "/opt/matrix-discord-bridge-new/misc.py", line 49, in wrapper
    raise RequestError(
errors.RequestError: Failed to get response from 'http://127.0.0.1:8008/_matrix/client/r0/directory/room/%23_discord_NEW_ID%3Amyserver.com?':
```
I also tried reversing the order of new and old id in your patch, and restoring the database how it previously was.

When restoring the database to have the OLD_ID for discord, it did not produce any errors for quite a while, then gave this error, not sure if related though
```
2023-02-21 00:59:58 appservice:ERROR:Exception in 'receive_event':
Traceback (most recent call last):
  File "/opt/matrix-discord-bridge-new/misc.py", line 28, in wrapper
    return fn(self, *args, **kwargs)
  File "/opt/matrix-discord-bridge-new/appservice.py", line 87, in receive_event
    self.handle_event(event)
  File "/opt/matrix-discord-bridge-new/appservice.py", line 66, in handle_event
    func(obj)
  File "/opt/matrix-discord-bridge-new/main.py", line 106, in on_message
    webhook = self.discord.get_webhook(
  File "/opt/matrix-discord-bridge-new/main.py", line 665, in get_webhook
    webhook = next(
  File "/opt/matrix-discord-bridge-new/main.py", line 667, in <genexpr>
    dict_cls(webhook, discord.Webhook)
  File "/opt/matrix-discord-bridge-new/misc.py", line 18, in dict_cls
    return cls(**filtered_dict)
TypeError: __init__() missing 1 required positional argument: 'token'
```

**Comment by git-bruh** [comment]
Ah sorry I messed up the order. The order should've been as you said:

```diff
+        if id == "5678": # NEW_ID
+            id = "1234" # OLD_ID
```

The other database change is correct logically

With both these changes, the flow should go like so:

Discord (new channel) -> Matrix (old room) // Due to hardcoded hack
Matrix (old room) -> Discord (new channel) // Due to database change

Can you stash your local changes and try both these again?

**Comment by Cknight70** [comment]
Hey sorry for the late reply, I'm happy to say this did make messages appear in the matrix room. However I am still getting the error from my last post. I tried deleting the webhook on discord to see if that could fix it. When I open the bot in console there is one more line 
```127.0.0.1 - - [27/Feb/2023 11:47:52] "PUT /transactions/6386118?access_token=<MYREALHS_TOKEN> HTTP/1.1" 500 807```

**Comment by git-bruh** [comment]
Hmm I think I had that problem once too, I didn't investigate much and just added a duct tape fix to change the webhook name here: https://github.com/git-bruh/matrix-discord-bridge/blob/main/appservice/main.py#L464

You can change it to say, `self.webhook_name = "matrix_bridge__"`

**Comment by Cknight70** [comment]
thanks for your help
